version: "3.9" 
  services:
    mysql:
      container_name: mysql
      image: mysql
      ports:
      - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root                   
      volumes:
        - ./data:/var/lib/mysql                         
        - ./src/main/db:/docker-entrypoint-initdb.d/:ro 
    web:
      container_name: tomcat
      build: .
      ports:
        - "8080:8080"
